name: Deploy to Firebase
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Repoyu clone'la
      - uses: actions/checkout@v4

      # 2. Dizin yapısını göster (tree komutu alternatifi)
      - name: Debug - Show Directory Structure
        run: |
          echo "### Ana Dizin Yapısı ###"
          ls -la
          echo "### public/ Klasörü İçeriği ###"
          ls -la public/ || echo "public/ klasörü bulunamadı!"
          echo "### firebase.json İçeriği ###"
          cat firebase.json || echo "firebase.json bulunamadı!"

      # 3. Node.js ve Firebase CLI kurulumu
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest

      # 4. Firebase Deploy
      - name: Deploy to Firebase
        run: firebase deploy --only hosting --non-interactive --debug
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
